# user-auth-spec.yaml


openapi: 3.0.0
info:
  title: User-Authentication
  description: Report Progress API specification outlines all that allows user to log in to their account
  version: 0.1.0
servers:
# the dash '-' indicates an array
  - url: http://localhost:8080/v1 # 1
    description: Developer Server
  - url: http://localhost/v1
    description: Production Server
tags: #5a
# set the grouping of operations
  - name: OAuth2
    description: User Authentication

paths:
  /login:
    post:
      summary: Authenticate User
      description: Todo
      tags:
        - OAuth2
      operationId: userLogin
      requestBody:
        $ref: '#/components/requestBody/userBody'
      responses: # 3
        200:    # status code
          $ref: '#/components/responses/Success'
          # Not create this. 
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    tokenBody:
      required:
        - scope 
        - expiresIn
        - refreshToken
        - accessToken
        - developerEmail
      properties:
        scope:
          type: string
          example: 'read, write'
        expiresIn:
          type: integer
          format: int64
          example: 3600
        refreshToken:
          type: string
          format: byte
          example: kkj5h3kj4h53jkh453ljk4h3kj
        accessToken:
          type: string
          format: byte
          example: kkj5h3kj4h53jkh453ljk4h3kj
        developerEmail:
          type: string
          format: email
          example: 'james.hemings@piecemeal.io'
        
    requestBody:
      required:    
        - email
        - password
      type: object
      properties:
        email:
          type: string
          format: email
          # for validating email; standard is JS
          # https://www.w3resource.com/javascript/form/email-validation.php
          pattern: ' /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/'
          minLength: 10
          example: 'james.hemings@piecemeal.io'
        password:
          type: string
          format: password
          minLength: 8
          example: 'k5lk3&0d'

    body_response_error: # 8
      required:
        - code_error
        - message
      type:
        object
      properties:
        code_error:
          type: integer
          format: int64
          example: 123
        message:
          type: string
          example: message_to_show_from_server

  requestBody:
    userBody:
      description: User JSON object required
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/requestBody'
  responses: # 6
    NotFound:
      BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'
    Success:
      description: Ok # same as "status message in spec"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tokenBody'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'
    ServerError: #8 
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'
